/**
 * =============[Portfolio CMS]=============
 * This is the version file that is responsible for storing
 * the current version of PortfolioCMS.
 * 
 * Please do not edit this file.
 * =============[Portfolio CMS]=============
 */
const major = 1;
const minor = 0;
const bug = 0;
const suffix = "-BETA-RC3";

function getVersionString() {
    return `${major}.${minor}.${bug}${suffix}`;
}

module.exports = {
    major: major,
    minor: minor,
    bug: bug,
    suffix: suffix,
    getVersionString: getVersionString
};